name: my_todo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  dynamic_color: ^1.6.7
  firebase_core: ^2.16.0
  firebase_database: ^10.2.6
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: glock
      fonts:
        - asset: assets/fonts/Gloock-regular.ttf
    - family: comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa.ttf

  assets:
    - assets/img/